/** @format */

const ROLE = {
  SUPERADMIN: "SUPERADMIN",
  ADMIN: "ADMIN",
};

const AVAILABILITY = {
  FULL_BOOKED: "FULL_BOOKED",
  OPEN_SEAT: "OPEN_SEAT",
};

const STATUS = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
};

const CATEGORIES = [
  { IT_TRAINING: "IT_TRAINING" },
  { IT_CONSULTANT: "IT_CONSULTANT" },
  { IT_SUPPORT: "IT_SUPPORT" },
];

const SKILL_LEVELS = [
  { BEGINNER: "BEGINNER" },
  { INTERMEDIATE: "INTERMEDIATE" },
  { EXPERT: "EXPERT" },
];

const LANGUAGES = [{ INDONESIA: "INDONESIA" }, { INGGRIS: "INGGRIS" }];

const ARTICLE_STATUS = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  ARCHIVED: "ARCHIVED",
};

const ARTICLE_CATEGORIES = {
  GENERAL: "GENERAL",
  IT_TRAINING: "IT_TRAINING",
  IT_CONSULTANT: "IT_CONSULTANT",
  CAREER_TIPS: "CAREER_TIPS",
  INDUSTRY_NEWS: "INDUSTRY_NEWS",
};

const JOB_TYPE = {
  FULL_TIME: "FULL_TIME",
  PART_TIME: "PART_TIME",
  CONTRACT: "CONTRACT",
  INTERNSHIP: "INTERNSHIP",
  FREELANCE: "FREELANCE",
};

const EXPERIENCE_LEVEL = {
  ENTRY: "ENTRY",
  MID: "MID",
  SENIOR: "SENIOR",
  LEAD: "LEAD",
  EXECUTIVE: "EXECUTIVE",
};

const JOB_STATUS = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  CLOSED: "CLOSED",
  ARCHIVED: "ARCHIVED",
};

const APPLICATION_STATUS = {
  PENDING: "PENDING",
  UNDER_REVIEW: "UNDER_REVIEW",
  SHORTLISTED: "SHORTLISTED",
  INTERVIEW: "INTERVIEW",
  REJECTED: "REJECTED",
  HIRED: "HIRED",
};

const RefreshToken = "exc_refresh_token";

module.exports = {
  ROLE,
  AVAILABILITY,
  STATUS,
  CATEGORIES,
  SKILL_LEVELS,
  LANGUAGES,
  ARTICLE_STATUS,
  ARTICLE_CATEGORIES,
  JOB_TYPE,
  EXPERIENCE_LEVEL,
  JOB_STATUS,
  APPLICATION_STATUS,
  RefreshToken,
};
